using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text.Json.Nodes;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Media.Imaging;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using FlipPix.ComfyUI.Services;
using FlipPix.Core.Interfaces;
using FlipPix.UI.Models;
using FlipPix.UI.Services;
using Application = System.Windows.Application;

namespace FlipPix.UI.ViewModels.Video
{
    /// <summary>
    /// H3 Batch Upscale — scans a folder for preview videos (generated by H3 Video Editor before upscale),
    /// shows them in a browser grid, and allows batch latent upscaling of selected videos.
    ///
    /// Uses the MinimaxH3LatentUpscaler3D workflow to upscale videos in H3 latent space,
    /// which produces better quality than pixel-space upscaling.
    /// </summary>
    public partial class H3BatchUpscaleViewModel : ObservableObject, IH3BatchUpscaleHost
    {
        private readonly ComfyUIService _comfyUIService;
        private readonly IAppLogger _logger;
        private readonly FlipPix.Core.Services.SettingsService _settingsService;
        private readonly WorkflowQueueCoordinator _workflowCoordinator;
        private readonly IFileDialogService _fileDialogService;

        private readonly ObservableCollection<H3BatchUpscaleItem> _all = new();
        private CancellationTokenSource? _runCts;

        public H3BatchUpscaleViewModel(
            ComfyUIService comfyUIService,
            LMStudioService lmStudioService,
            IAppLogger logger,
            FlipPix.Core.Services.SettingsService settingsService,
            IServiceProvider? serviceProvider,
            WorkflowQueueCoordinator workflowCoordinator,
            IFileDialogService fileDialogService)
        {
            _comfyUIService = comfyUIService;
            _logger = logger;
            _settingsService = settingsService;
            _workflowCoordinator = workflowCoordinator;
            _fileDialogService = fileDialogService;

            // Initialize commands
            BrowseFolderCommand = new RelayCommand(() => _ = BrowseFolderAsync(), () => !IsScanning && !IsUpscaling);
            RescanCommand = new RelayCommand(() => _ = ScanAsync(), () => !IsScanning && !IsUpscaling);
            SelectAllCommand = new RelayCommand(() => SetAllSelected(true), () => Items.Count > 0);
            SelectNoneCommand = new RelayCommand(() => SetAllSelected(false), () => HasSelection);
            InvertSelectionCommand = new RelayCommand(InvertSelection, () => Items.Count > 0);
            UpscaleSelectedCommand = new RelayCommand(() => _ = RunUpscaleAsync(), () => HasSelection && !IsUpscaling);
            StopUpscaleCommand = new RelayCommand(StopRun, () => IsUpscaling);
            ToggleMuteCommand = new RelayCommand(() => IsPreviewMuted = !IsPreviewMuted);
            ZoomTilesInCommand = new RelayCommand(() => TileSize += TileSizeStep, () => TileSize < MaxTileSize);
            ZoomTilesOutCommand = new RelayCommand(() => TileSize -= TileSizeStep, () => TileSize > MinTileSize);
            OpenScanFolderCommand = new RelayCommand(OpenScanFolder, () => HasScanFolder);
            CopyLogCommand = new RelayCommand(CopyLog);
            ClearLogCommand = new RelayCommand(ClearLog);

            // Load saved settings
            _scanFolder = settingsService.Settings?.H3BatchUpscaleFolder ?? string.Empty;
            if (string.IsNullOrWhiteSpace(_scanFolder)) _scanFolder = DefaultScanFolder();

            var upscaleSettings = settingsService.Settings?.H3BatchUpscale;
            if (upscaleSettings != null)
            {
                _upscaleFactor = upscaleSettings.UpscaleFactor;
                _refineAmount = upscaleSettings.RefineAmount;
                _shiftVideo = upscaleSettings.ShiftVideo;
                _shiftAudio = upscaleSettings.ShiftAudio;
                _crf = upscaleSettings.Crf;
            }

            AddLog("H3 Batch Upscale initialized — point it at a folder of H3 preview videos, " +
                   "tick the ones to upscale, and click Upscale Selected.");

            // Initial scan (off the constructor's thread)
            _ = ScanAsync();
        }

        // ── Logging ────────────────────────────────────────────────────────────────────────────────

        public ObservableCollection<string> LogMessages { get; } = new();

        private void AddLog(string message)
        {
            var timestamp = DateTime.Now.ToString("HH:mm:ss");
            Application.Current?.Dispatcher.Invoke(() =>
            {
                LogMessages.Insert(0, $"[{timestamp}] {message}");
                while (LogMessages.Count > 100) LogMessages.RemoveAt(LogMessages.Count - 1);
            });
        }

        private void CopyLog()
        {
            if (LogMessages.Count == 0) return;
            var logText = string.Join(Environment.NewLine, LogMessages.Reverse());
            System.Windows.Clipboard.SetText(logText);
            AddLog("Log copied to clipboard");
        }

        private void ClearLog() => LogMessages.Clear();

        public RelayCommand CopyLogCommand { get; }
        public RelayCommand ClearLogCommand { get; }

        // ── Folder Selection ───────────────────────────────────────────────────────────────────────

        [ObservableProperty]
        private string _scanFolder = string.Empty;

        [ObservableProperty]
        private bool _folderExists;

        [ObservableProperty]
        private bool _includeSubfolders = true;

        [ObservableProperty]
        private bool _hideAlreadyUpscaled;

        [ObservableProperty]
        private string _filterText = string.Empty;

        public bool HasScanFolder => FolderExists;

        partial void OnScanFolderChanged(string value)
        {
            var settings = _settingsService.Settings;
            if (settings != null)
            {
                settings.H3BatchUpscaleFolder = value;
                _settingsService.SaveSettings(settings);
            }
            _ = ScanAsync();
        }

        partial void OnIncludeSubfoldersChanged(bool value) => _ = ScanAsync();
        partial void OnHideAlreadyUpscaledChanged(bool value) => ApplyFilter();
        partial void OnFilterTextChanged(string value) => ApplyFilter();

        private string DefaultScanFolder()
        {
            var root = _settingsService.Settings?.OutputFolderPath;
            return string.IsNullOrWhiteSpace(root) ? string.Empty : Path.Combine(root, "video");
        }

        private string OutputDirectory()
        {
            var root = _settingsService.Settings?.OutputFolderPath ?? string.Empty;
            return Path.Combine(root, "H3BatchUpscale");
        }

        public RelayCommand BrowseFolderCommand { get; }
        public RelayCommand RescanCommand { get; }
        public RelayCommand OpenScanFolderCommand { get; }

        private async Task BrowseFolderAsync()
        {
            var picked = await _fileDialogService.OpenFolderDialogAsync(
                "Folder of H3 preview videos to scan",
                HasScanFolder ? ScanFolder : null,
                persistKey: "h3batchupscale.scan");
            if (!string.IsNullOrWhiteSpace(picked)) ScanFolder = picked;
        }

        private void OpenScanFolder()
        {
            try
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = ScanFolder,
                    UseShellExecute = true
                });
            }
            catch (Exception ex) { AddLog($"Could not open the folder: {ex.Message}"); }
        }

        // ── Video Browser ──────────────────────────────────────────────────────────────────────────

        public ObservableCollection<H3BatchUpscaleItem> Items { get; } = new();

        [ObservableProperty]
        private bool _isScanning;

        [ObservableProperty]
        private bool _isUpscaling;

        [ObservableProperty]
        private string _scanStatus = string.Empty;

        [ObservableProperty]
        private double _progress;

        public int SelectedCount => Items.Count(i => i.IsSelected);
        public bool HasSelection => SelectedCount > 0;
        public bool HasItems => Items.Count > 0;

        public string SelectionSummary
        {
            get
            {
                if (_all.Count == 0) return "No videos found in this folder.";
                var shown = Items.Count == _all.Count ? $"{_all.Count} video(s)" : $"{Items.Count} of {_all.Count} video(s)";
                return SelectedCount == 0 ? $"{shown} — tick the ones worth upscaling."
                                          : $"{shown}, {SelectedCount} selected.";
            }
        }

        partial void OnIsScanningChanged(bool value) => RefreshCommands();
        partial void OnIsUpscalingChanged(bool value) => RefreshCommands();

        public async Task ScanAsync()
        {
            if (IsScanning || IsUpscaling) return;
            var folder = ScanFolder;

            IsScanning = true;
            ScanStatus = "Scanning...";

            try
            {
                var (exists, found) = await Task.Run(() =>
                {
                    if (string.IsNullOrWhiteSpace(folder) || !Directory.Exists(folder))
                        return (false, new List<H3BatchUpscaleItem>());
                    var items = ReadFolder(folder);

                    // Check for already upscaled videos
                    var outDir = OutputDirectory();
                    if (Directory.Exists(outDir))
                    {
                        foreach (var item in items)
                        {
                            var candidate = Path.Combine(outDir, Path.GetFileName(item.VideoPath));
                            if (File.Exists(candidate)) item.UpscaledPath = candidate;
                        }
                    }
                    return (true, items);
                });

                FolderExists = exists;
                OnPropertyChanged(nameof(HasScanFolder));
                OpenScanFolderCommand.NotifyCanExecuteChanged();

                if (!exists)
                {
                    _all.Clear();
                    Items.Clear();
                    ScanStatus = string.IsNullOrWhiteSpace(folder)
                        ? "Choose a folder containing H3 preview videos."
                        : $"Folder does not exist: {folder}";
                    RefreshCounts();
                    return;
                }

                Application.Current.Dispatcher.Invoke(() =>
                {
                    var previous = _all.ToDictionary(i => i.Key, i => i);
                    _all.Clear();
                    foreach (var item in found)
                    {
                        if (previous.TryGetValue(item.Key, out var old))
                        {
                            item.IsSelected = old.IsSelected;
                            item.Thumbnail = old.Thumbnail;
                            item.Status = old.Status;
                        }
                        item.PropertyChanged += ItemPropertyChanged;
                        _all.Add(item);
                    }
                    ApplyFilter();
                    ScanStatus = _all.Count == 0
                        ? "No MP4 videos found here."
                        : $"{_all.Count} video(s) found.";
                });

                await FillThumbnailsAsync();
            }
            catch (Exception ex)
            {
                AddLog($"Scan failed: {ex.Message}");
                ScanStatus = $"Scan failed: {ex.Message}";
            }
            finally { IsScanning = false; }
        }

        private List<H3BatchUpscaleItem> ReadFolder(string folder)
        {
            var option = IncludeSubfolders ? SearchOption.AllDirectories : SearchOption.TopDirectoryOnly;
            var videos = Directory.EnumerateFiles(folder, "*.mp4", option)
                                  .Where(f => !Path.GetFileName(f).StartsWith("upscale_", StringComparison.OrdinalIgnoreCase))
                                  .ToList();

            var items = new List<H3BatchUpscaleItem>();
            foreach (var video in videos)
            {
                items.Add(new H3BatchUpscaleItem(this, video));
            }

            return items.OrderByDescending(i => new FileInfo(i.VideoPath).CreationTime).ToList();
        }

        private void ItemPropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(H3BatchUpscaleItem.IsSelected)) RefreshCounts();
        }

        private void ApplyFilter()
        {
            var needle = FilterText.Trim();
            IEnumerable<H3BatchUpscaleItem> query = _all;
            if (needle.Length > 0)
                query = query.Where(i => i.SearchText.Contains(needle, StringComparison.OrdinalIgnoreCase));
            if (HideAlreadyUpscaled)
                query = query.Where(i => !i.HasUpscale);

            var filtered = query.ToList();
            Items.Clear();
            foreach (var item in filtered)
                Items.Add(item);
            RefreshCounts();
        }

        private void RefreshCounts()
        {
            OnPropertyChanged(nameof(SelectedCount));
            OnPropertyChanged(nameof(HasSelection));
            OnPropertyChanged(nameof(HasItems));
            OnPropertyChanged(nameof(SelectionSummary));
            RefreshCommands();
        }

        private void RefreshCommands()
        {
            BrowseFolderCommand.NotifyCanExecuteChanged();
            RescanCommand.NotifyCanExecuteChanged();
            SelectAllCommand.NotifyCanExecuteChanged();
            SelectNoneCommand.NotifyCanExecuteChanged();
            InvertSelectionCommand.NotifyCanExecuteChanged();
            UpscaleSelectedCommand.NotifyCanExecuteChanged();
            StopUpscaleCommand.NotifyCanExecuteChanged();
            ZoomTilesInCommand.NotifyCanExecuteChanged();
            ZoomTilesOutCommand.NotifyCanExecuteChanged();
        }

        private async Task FillThumbnailsAsync()
        {
            string? ffmpegPath = null;

            foreach (var item in _all.ToList())
            {
                if (item.Thumbnail != null) continue;

                BitmapImage? bmp = null;

                // First try to find existing thumbnail
                var thumbPath = FindExistingThumbnail(item.VideoPath);
                if (thumbPath != null)
                {
                    bmp = await Task.Run(() => LoadThumbnail(thumbPath));
                }

                // Fallback to FFmpeg extraction
                if (bmp == null)
                {
                    ffmpegPath ??= FindFFmpeg();
                    if (ffmpegPath != null)
                    {
                        bmp = await Task.Run(() => ExtractThumbnailWithFFmpeg(item.VideoPath, ffmpegPath));
                    }
                }

                if (bmp != null)
                {
                    Application.Current?.Dispatcher.Invoke(() => item.Thumbnail = bmp);
                }
            }
        }

        private BitmapImage? LoadThumbnail(string path)
        {
            try
            {
                var bmp = new BitmapImage();
                bmp.BeginInit();
                bmp.CacheOption = BitmapCacheOption.OnLoad;
                bmp.UriSource = new Uri(path, UriKind.Absolute);
                bmp.DecodePixelWidth = 160;
                bmp.EndInit();
                bmp.Freeze();
                return bmp;
            }
            catch { return null; }
        }

        private BitmapImage? ExtractThumbnailWithFFmpeg(string videoPath, string ffmpegPath)
        {
            try
            {
                var outPath = Path.Combine(Path.GetTempPath(), $"h3batch_thumb_{Guid.NewGuid():N}.png");
                var psi = new System.Diagnostics.ProcessStartInfo
                {
                    FileName = ffmpegPath,
                    Arguments = $"-y -i \"{videoPath}\" -frames:v 1 -q:v 3 \"{outPath}\"",
                    UseShellExecute = false,
                    RedirectStandardError = true,
                    CreateNoWindow = true
                };

                using (var p = System.Diagnostics.Process.Start(psi))
                {
                    if (p == null) return null;
                    p.StandardError.ReadToEnd();
                    p.WaitForExit(10000);
                }

                if (!File.Exists(outPath) || new FileInfo(outPath).Length == 0) return null;

                var bmp = LoadThumbnail(outPath);
                try { File.Delete(outPath); } catch { }
                return bmp;
            }
            catch { return null; }
        }

        /// <summary>
        /// Finds an existing thumbnail for a video file.
        /// H3 Video Editor generates thumbnails like: clip_00001_thumb_00001_.png
        /// Video files are named like: clip_00001_00001_.mp4 (clip_{index}_{render}_.mp4)
        /// </summary>
        private string? FindExistingThumbnail(string videoPath)
        {
            try
            {
                var dir = Path.GetDirectoryName(videoPath);
                if (string.IsNullOrEmpty(dir)) return null;

                var videoName = Path.GetFileNameWithoutExtension(videoPath);

                // Extract clip index from video name like "clip_00002_00001_" -> "clip_00002"
                // Pattern: clip_{clipIndex}_{renderIndex}_ -> thumbnail is clip_{clipIndex}_thumb_*
                if (videoName.StartsWith("clip_", StringComparison.OrdinalIgnoreCase))
                {
                    var parts = videoName.Split('_');
                    if (parts.Length >= 2)
                    {
                        var clipPrefix = $"{parts[0]}_{parts[1]}"; // "clip_00002"
                        var thumbs = Directory.GetFiles(dir, $"{clipPrefix}_thumb_*.png");
                        if (thumbs.Length > 0)
                            return thumbs[0];
                    }
                }

                // Try exact match: video.mp4 -> video_thumb_*.png
                var exactThumbs = Directory.GetFiles(dir, $"{videoName}_thumb_*.png");
                if (exactThumbs.Length > 0)
                    return exactThumbs[0];

                // Try any PNG starting with video name
                var candidates = Directory.GetFiles(dir, "*.png")
                    .Where(f => Path.GetFileName(f).StartsWith(videoName, StringComparison.OrdinalIgnoreCase))
                    .ToArray();
                if (candidates.Length > 0)
                    return candidates[0];
            }
            catch { }

            return null;
        }

        private string? FindFFmpeg()
        {
            var candidates = new[]
            {
                @"C:\ffmpeg\bin\ffmpeg.exe",
                @"C:\Program Files\ffmpeg\bin\ffmpeg.exe",
                Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "ffmpeg", "bin", "ffmpeg.exe"),
                Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "ffmpeg", "bin", "ffmpeg.exe"),
            };

            foreach (var path in candidates)
            {
                if (File.Exists(path)) return path;
            }

            // Try PATH
            var pathEnv = Environment.GetEnvironmentVariable("PATH") ?? string.Empty;
            foreach (var dir in pathEnv.Split(Path.PathSeparator))
            {
                try
                {
                    var candidate = Path.Combine(dir, "ffmpeg.exe");
                    if (File.Exists(candidate)) return candidate;
                }
                catch { }
            }

            return null;
        }

        // ── Selection Commands ─────────────────────────────────────────────────────────────────────

        public RelayCommand SelectAllCommand { get; }
        public RelayCommand SelectNoneCommand { get; }
        public RelayCommand InvertSelectionCommand { get; }

        private void SetAllSelected(bool selected)
        {
            foreach (var item in Items)
                item.IsSelected = selected;
        }

        private void InvertSelection()
        {
            foreach (var item in Items)
                item.IsSelected = !item.IsSelected;
        }

        // ── Preview Player ─────────────────────────────────────────────────────────────────────────

        [ObservableProperty]
        private string? _activePreviewUri;

        [ObservableProperty]
        private string _activePreviewLabel = string.Empty;

        [ObservableProperty]
        private bool _isPreviewMuted = true;

        public RelayCommand ToggleMuteCommand { get; }

        // ── Tile Zoom ──────────────────────────────────────────────────────────────────────────────

        private const double MinTileSize = 80;
        private const double MaxTileSize = 300;
        private const double TileSizeStep = 20;

        [ObservableProperty]
        private double _tileSize = 132;

        public RelayCommand ZoomTilesInCommand { get; }
        public RelayCommand ZoomTilesOutCommand { get; }

        // ── Upscale Settings ───────────────────────────────────────────────────────────────────────

        [ObservableProperty]
        private double _upscaleFactor = 2.0;

        [ObservableProperty]
        private double _refineAmount = 0.2;

        [ObservableProperty]
        private int _shiftVideo = 12;

        [ObservableProperty]
        private int _shiftAudio = 3;

        [ObservableProperty]
        private int _crf = 19;

        partial void OnUpscaleFactorChanged(double value) => SaveSettings();
        partial void OnRefineAmountChanged(double value) => SaveSettings();
        partial void OnShiftVideoChanged(int value) => SaveSettings();
        partial void OnShiftAudioChanged(int value) => SaveSettings();
        partial void OnCrfChanged(int value) => SaveSettings();

        private void SaveSettings()
        {
            var settings = _settingsService.Settings;
            if (settings == null) return;

            settings.H3BatchUpscale ??= new FlipPix.Core.Models.H3BatchUpscaleSettings();
            settings.H3BatchUpscale.UpscaleFactor = UpscaleFactor;
            settings.H3BatchUpscale.RefineAmount = RefineAmount;
            settings.H3BatchUpscale.ShiftVideo = ShiftVideo;
            settings.H3BatchUpscale.ShiftAudio = ShiftAudio;
            settings.H3BatchUpscale.Crf = Crf;

            _settingsService.SaveSettings(settings);
        }

        // ── Upscale Execution ──────────────────────────────────────────────────────────────────────

        public RelayCommand UpscaleSelectedCommand { get; }
        public RelayCommand StopUpscaleCommand { get; }

        private async Task RunUpscaleAsync()
        {
            if (!HasSelection || IsUpscaling) return;

            var selected = Items.Where(i => i.IsSelected && !i.HasUpscale).ToList();
            if (selected.Count == 0)
            {
                AddLog("All selected videos have already been upscaled.");
                return;
            }

            IsUpscaling = true;
            _runCts = new CancellationTokenSource();
            Progress = 0;

            var outDir = OutputDirectory();
            Directory.CreateDirectory(outDir);

            int completed = 0;
            int total = selected.Count;

            try
            {
                using var lease = await _workflowCoordinator.AcquireAsync("h3_batch_upscale", _runCts.Token);

                foreach (var item in selected)
                {
                    if (_runCts.Token.IsCancellationRequested) break;

                    item.IsBusy = true;
                    item.Status = "Upscaling...";
                    ScanStatus = $"Upscaling {completed + 1}/{total}: {item.FileName}";

                    try
                    {
                        // Upload the video
                        AddLog($"Uploading: {item.FileName}");
                        var uploadedName = await _comfyUIService.UploadVideoAsync(item.VideoPath, _runCts.Token);
                        AddLog($"Uploaded as: {uploadedName}");

                        // Build and execute workflow
                        var (workflow, saveNodeId) = BuildUpscaleWorkflow(uploadedName, item.FileName);

                        AddLog($"Submitting upscale workflow ({UpscaleFactor}x)...");
                        var progress = new Progress<FlipPix.ComfyUI.Models.ProgressMessage>(msg =>
                        {
                            if (msg.Data?.Value != null && msg.Data?.Max != null && msg.Data.Max > 0)
                            {
                                var itemProgress = (double)msg.Data.Value / msg.Data.Max * 100;
                                var overallProgress = ((completed + itemProgress / 100) / total) * 100;
                                Progress = overallProgress;
                                item.Status = $"Upscaling: {itemProgress:F0}%";
                            }
                        });

                        var promptId = await _comfyUIService.ExecuteWorkflowAsync(workflow, progress, _runCts.Token);

                        if (!string.IsNullOrEmpty(promptId))
                        {
                            var outputPath = await ResolveOutputAsync(promptId, saveNodeId, item.FileName);
                            if (!string.IsNullOrEmpty(outputPath))
                            {
                                item.UpscaledPath = outputPath;
                                item.Status = "Done";
                                AddLog($"Upscaled: {item.FileName} -> {Path.GetFileName(outputPath)}");
                            }
                            else
                            {
                                item.Status = "Output not found";
                                AddLog($"Warning: {item.FileName} - output path not resolved");
                            }
                        }
                        else
                        {
                            item.Status = "Failed";
                            AddLog($"Error: {item.FileName} - empty prompt ID");
                        }

                        completed++;
                    }
                    catch (Exception ex)
                    {
                        item.Status = $"Error: {ex.Message}";
                        AddLog($"Error upscaling {item.FileName}: {ex.Message}");
                    }
                    finally
                    {
                        item.IsBusy = false;
                    }
                }

                Progress = 100;
                ScanStatus = $"Completed {completed}/{total} upscales.";
                AddLog($"Batch upscale finished: {completed}/{total}");
            }
            catch (OperationCanceledException)
            {
                ScanStatus = "Upscale cancelled.";
                AddLog("Batch upscale cancelled by user.");
            }
            catch (Exception ex)
            {
                ScanStatus = $"Upscale failed: {ex.Message}";
                AddLog($"Batch upscale failed: {ex.Message}");
            }
            finally
            {
                IsUpscaling = false;
                _runCts?.Dispose();
                _runCts = null;
            }
        }

        private void StopRun()
        {
            _runCts?.Cancel();
            AddLog("Stopping upscale...");
        }

        private (JsonObject workflow, string saveNodeId) BuildUpscaleWorkflow(string uploadedVideoName, string outputName)
        {
            AddLog($"Building H3 Latent Upscale workflow for: {uploadedVideoName}");
            AddLog($"Upscale factor: {UpscaleFactor}x, Refine amount: {RefineAmount}");

            int refineSteps = RefineAmount >= 0.5 ? 10 : (RefineAmount >= 0.3 ? 8 : 6);
            var outputPrefix = $"H3BatchUpscale/{Path.GetFileNameWithoutExtension(outputName)}_up{UpscaleFactor:F1}x";

            var workflow = new JsonObject
            {
                // UNet Model
                ["unet"] = new JsonObject
                {
                    ["class_type"] = "UNETLoader",
                    ["inputs"] = new JsonObject
                    {
                        ["unet_name"] = "h3-minimax/minimax_h3_fused_refdelta_r1024_turbo8_mystic07_int8_convrot.safetensors",
                        ["weight_dtype"] = "default"
                    }
                },

                // CLIP
                ["clip"] = new JsonObject
                {
                    ["class_type"] = "CLIPLoader",
                    ["inputs"] = new JsonObject
                    {
                        ["clip_name"] = "qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors",
                        ["type"] = "minimax",
                        ["device"] = "default"
                    }
                },

                // Video VAE
                ["vae_video"] = new JsonObject
                {
                    ["class_type"] = "VAELoader",
                    ["inputs"] = new JsonObject
                    {
                        ["vae_name"] = "minimax_h3_video_vae_int8_convrot.safetensors"
                    }
                },

                // Audio VAE
                ["vae_audio"] = new JsonObject
                {
                    ["class_type"] = "VAELoader",
                    ["inputs"] = new JsonObject
                    {
                        ["vae_name"] = "minimax_h3_audio_vae_fp32.safetensors"
                    }
                },

                // Sigma shift
                ["shift"] = new JsonObject
                {
                    ["class_type"] = "MiniMaxH3SigmaShift",
                    ["inputs"] = new JsonObject
                    {
                        ["model"] = new JsonArray { "unet", 0 },
                        ["shift_video"] = (double)ShiftVideo,
                        ["shift_audio"] = (double)ShiftAudio
                    }
                },

                // Load video
                ["load_video"] = new JsonObject
                {
                    ["class_type"] = "VHS_LoadVideo",
                    ["inputs"] = new JsonObject
                    {
                        ["video"] = uploadedVideoName,
                        ["force_rate"] = 0,
                        ["custom_width"] = 0,
                        ["custom_height"] = 0,
                        ["frame_load_cap"] = 0,
                        ["skip_first_frames"] = 0,
                        ["select_every_nth"] = 1,
                        ["format"] = "None"
                    }
                },

                // Encode video to latent
                ["vae_encode_video"] = new JsonObject
                {
                    ["class_type"] = "VAEEncode",
                    ["inputs"] = new JsonObject
                    {
                        ["pixels"] = new JsonArray { "load_video", 0 },
                        ["vae"] = new JsonArray { "vae_video", 0 }
                    }
                },

                // Encode audio to latent
                ["vae_encode_audio"] = new JsonObject
                {
                    ["class_type"] = "VAEEncodeAudio",
                    ["inputs"] = new JsonObject
                    {
                        ["audio"] = new JsonArray { "load_video", 2 },
                        ["vae"] = new JsonArray { "vae_audio", 0 }
                    }
                },

                // Latent upscale
                ["latent_upscale"] = new JsonObject
                {
                    ["class_type"] = "MinimaxH3LatentUpscaler3D",
                    ["inputs"] = new JsonObject
                    {
                        ["latent"] = new JsonArray { "vae_encode_video", 0 },
                        ["model_name"] = "minimax_h3_latent_upscaler_3d_conv_v1_fp16.safetensors",
                        ["mode"] = "scale by multiplier",
                        ["mode.scale"] = UpscaleFactor,
                        ["align"] = 32,
                        ["enable_temporal_chunking"] = true,
                        ["force_unload"] = true,
                        ["device"] = "cuda",
                        ["precision"] = "fp16"
                    }
                },

                // Concat video + audio latents
                ["concat_av"] = new JsonObject
                {
                    ["class_type"] = "LTXVConcatAVLatent",
                    ["inputs"] = new JsonObject
                    {
                        ["video_latent"] = new JsonArray { "latent_upscale", 0 },
                        ["audio_latent"] = new JsonArray { "vae_encode_audio", 0 }
                    }
                },

                // Conditioning for refine pass
                ["conditioning"] = new JsonObject
                {
                    ["class_type"] = "CLIPTextEncode",
                    ["inputs"] = new JsonObject
                    {
                        ["clip"] = new JsonArray { "clip", 0 },
                        ["text"] = "Maintain original content. Enhance fine details, textures, and sharpness. Preserve motion, faces, and composition. High quality video upscale."
                    }
                },

                // Guider
                ["guider"] = new JsonObject
                {
                    ["class_type"] = "BasicGuider",
                    ["inputs"] = new JsonObject
                    {
                        ["model"] = new JsonArray { "shift", 0 },
                        ["conditioning"] = new JsonArray { "conditioning", 0 }
                    }
                },

                // Scheduler
                ["sigmas"] = new JsonObject
                {
                    ["class_type"] = "BasicScheduler",
                    ["inputs"] = new JsonObject
                    {
                        ["model"] = new JsonArray { "shift", 0 },
                        ["scheduler"] = "simple",
                        ["steps"] = refineSteps,
                        ["denoise"] = RefineAmount
                    }
                },

                // Sampler select
                ["sampler_select"] = new JsonObject
                {
                    ["class_type"] = "KSamplerSelect",
                    ["inputs"] = new JsonObject
                    {
                        ["sampler_name"] = "res_multistep"
                    }
                },

                // Random noise
                ["noise"] = new JsonObject
                {
                    ["class_type"] = "RandomNoise",
                    ["inputs"] = new JsonObject
                    {
                        ["noise_seed"] = Random.Shared.NextInt64(0, 999_999_999_999_999L)
                    }
                },

                // Refine sampler
                ["refine_sampler"] = new JsonObject
                {
                    ["class_type"] = "SamplerCustomAdvanced",
                    ["inputs"] = new JsonObject
                    {
                        ["noise"] = new JsonArray { "noise", 0 },
                        ["guider"] = new JsonArray { "guider", 0 },
                        ["sampler"] = new JsonArray { "sampler_select", 0 },
                        ["sigmas"] = new JsonArray { "sigmas", 0 },
                        ["latent_image"] = new JsonArray { "concat_av", 0 }
                    }
                },

                // Decode video
                ["vae_decode_video"] = new JsonObject
                {
                    ["class_type"] = "VAEDecode",
                    ["inputs"] = new JsonObject
                    {
                        ["samples"] = new JsonArray { "refine_sampler", 0 },
                        ["vae"] = new JsonArray { "vae_video", 0 }
                    }
                },

                // Decode audio
                ["vae_decode_audio"] = new JsonObject
                {
                    ["class_type"] = "VAEDecodeAudio",
                    ["inputs"] = new JsonObject
                    {
                        ["samples"] = new JsonArray { "refine_sampler", 0 },
                        ["vae"] = new JsonArray { "vae_audio", 0 }
                    }
                },

                // Output
                ["output"] = new JsonObject
                {
                    ["class_type"] = "VHS_VideoCombine",
                    ["inputs"] = new JsonObject
                    {
                        ["images"] = new JsonArray { "vae_decode_video", 0 },
                        ["audio"] = new JsonArray { "vae_decode_audio", 0 },
                        ["frame_rate"] = 24,
                        ["loop_count"] = 0,
                        ["filename_prefix"] = outputPrefix,
                        ["format"] = "video/h264-mp4",
                        ["pix_fmt"] = "yuv420p",
                        ["crf"] = Crf,
                        ["save_metadata"] = false,
                        ["trim_to_audio"] = false,
                        ["pingpong"] = false,
                        ["save_output"] = true
                    }
                }
            };

            return (workflow, "output");
        }

        private async Task<string?> ResolveOutputAsync(string promptId, string saveNodeId, string originalName)
        {
            try
            {
                var byNode = await _comfyUIService.HttpClient.GetOutputsByNodeAsync(promptId, CancellationToken.None);
                if (byNode.TryGetValue(saveNodeId, out var outputs) && outputs.Count > 0)
                {
                    AddLog($"ComfyUI returned output: {outputs[0]}");

                    // Try to find the file locally
                    var settings = _settingsService.Settings;
                    var outputDir = !string.IsNullOrEmpty(settings?.OutputFolderPath)
                        ? Path.Combine(settings.OutputFolderPath, "H3BatchUpscale")
                        : OutputDirectory();

                    if (Directory.Exists(outputDir))
                    {
                        var pattern = Path.GetFileNameWithoutExtension(originalName) + "*";
                        var files = Directory.GetFiles(outputDir, pattern)
                                             .OrderByDescending(f => new FileInfo(f).CreationTime)
                                             .FirstOrDefault();
                        if (files != null) return files;
                    }

                    // Return the ComfyUI output path
                    return outputs[0];
                }
            }
            catch (Exception ex)
            {
                AddLog($"Error resolving output: {ex.Message}");
            }
            return null;
        }

        // ── IH3BatchUpscaleHost Implementation ─────────────────────────────────────────────────────

        public void PlayVideo(H3BatchUpscaleItem? item)
        {
            if (item == null) return;
            ActivePreviewUri = item.VideoPath;
            ActivePreviewLabel = item.FileName;
        }

        public void ToggleVideo(H3BatchUpscaleItem? item)
        {
            if (item != null)
                item.IsSelected = !item.IsSelected;
        }

        public void PlayUpscaled(H3BatchUpscaleItem? item)
        {
            if (item?.HasUpscale == true)
            {
                ActivePreviewUri = item.UpscaledPath;
                ActivePreviewLabel = $"{item.FileName} (upscaled)";
            }
        }

        public void RevealVideo(H3BatchUpscaleItem? item)
        {
            if (item == null) return;
            try
            {
                var path = item.HasUpscale ? item.UpscaledPath! : item.VideoPath;
                System.Diagnostics.Process.Start("explorer.exe", $"/select,\"{path}\"");
            }
            catch (Exception ex) { AddLog($"Could not reveal: {ex.Message}"); }
        }
    }
}
