using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using CommunityToolkit.Mvvm.Input;
using FlipPix.ComfyUI.Services;
using FlipPix.Core.Interfaces;
using FlipPix.UI.Linux.Models;
using FlipPix.UI.Linux.Services;
using Application = System.Windows.Application;
// MessageBox is fully qualified below: MsBox.Avalonia contributes a root
// namespace of the same name, so a using-alias would be a CS0576 conflict.

namespace FlipPix.UI.Linux.ViewModels.Video
{
    /// <summary>
    /// VR 180 — drop in a flat (rectilinear) video and get back a 360° equirectangular
    /// panorama, generated by outpainting each frame with the LTX-2.3-22B equirect IC-LoRA
    /// (workflow/video/ltx/VR180_Equirect_api.json). The result plays in any VR headset;
    /// VR180 viewers simply show the front hemisphere.
    /// </summary>
    public partial class Vr180ViewModel : VideoProcessingBaseViewModel
    {
        private const string WorkflowFileName = "workflow/video/ltx/VR180_Equirect_api.json";
        private const string OutputSubfolder = "vr180";
        private const string DepthSubfolder = "vr180_depth";

        // Workflow nodes driven from the UI.
        private const string LoadVideoNode = "5060";       // VHS_LoadVideo
        private const string EquirectNode = "5097";        // RectilinearToEquirect
        private const string PositiveNode = "2483";        // CLIP Text Encode (positive)
        private const string NegativeNode = "2612";        // CLIP Text Encode (negative)
        private const string SeedNode = "4832";            // RandomNoise

        public static readonly string[] ResolutionOptions = { "960×480", "1280×640", "1600×800", "1920×960" };

        private string QueueFilePath => Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
            "FlipPix", "queue", "vr180_queue.json");

        private readonly IFileDialogService _fileDialogService;
        private readonly LMStudioService _lmStudioService;
        private readonly ObservableCollection<Vr180QueueItem> _queue = new();
        private CancellationTokenSource? _queueCts;
        private CancellationTokenSource? _analyzeCts;

        public Vr180ViewModel(
            ComfyUIService comfyUIService,
            LMStudioService lmStudioService,
            IAppLogger logger,
            FlipPix.Core.Services.SettingsService settingsService,
            IServiceProvider? serviceProvider,
            WorkflowQueueCoordinator workflowCoordinator,
            IFileDialogService fileDialogService)
            : base(comfyUIService, logger, settingsService, serviceProvider, workflowCoordinator)
        {
            _lmStudioService = lmStudioService ?? throw new ArgumentNullException(nameof(lmStudioService));
            _fileDialogService = fileDialogService ?? throw new ArgumentNullException(nameof(fileDialogService));

            SelectVideoCommand = new RelayCommand(SelectVideo);
            AnalyzeCommand = new RelayCommand(async () => await AnalyzeAsync(), () => CanAnalyze);
            GenerateVideoCommand = new RelayCommand(AddToQueue, () => CanAddToQueue);
            RemoveQueueItemCommand = new RelayCommand<Vr180QueueItem>(RemoveQueueItem);
            ClearQueueCommand = new RelayCommand(ClearQueue, () => _queue.Any());
            StopQueueCommand = new RelayCommand(StopQueue, () => IsProcessingQueue);
            StartQueueCommand = new RelayCommand(async () => await ProcessQueueAsync(), () => HasQueueItems && !IsProcessingQueue);
            ReprocessAllFailedCommand = new RelayCommand(async () => await ReprocessAllFailedAsync(), () => HasFailedItems);
            PlayVideoCommand = new RelayCommand(PlayVideo, () => HasResult);
            OpenResultFolderCommand = new RelayCommand(OpenResultFolder, () => HasResult);
            SendToEditCameraCommand = new RelayCommand(SendToEditCamera, () => HasResult);

            _queue.CollectionChanged += (s, e) =>
            {
                OnPropertyChanged(nameof(HasQueueItems));
                UpdateQueueStatus();
                OnCanExecuteChanged();
            };

            AddLog("VR 180 initialized");
            LoadQueueFromFile();
        }

        #region Commands
        public ICommand SelectVideoCommand { get; }
        public RelayCommand AnalyzeCommand { get; }
        public RelayCommand GenerateVideoCommand { get; }
        public RelayCommand<Vr180QueueItem> RemoveQueueItemCommand { get; }
        public RelayCommand ClearQueueCommand { get; }
        public RelayCommand StopQueueCommand { get; }
        public RelayCommand StartQueueCommand { get; }
        public RelayCommand ReprocessAllFailedCommand { get; }
        public RelayCommand PlayVideoCommand { get; }
        public RelayCommand OpenResultFolderCommand { get; }
        public RelayCommand SendToEditCameraCommand { get; }

        public bool HasFailedItems => _queue.Any(x => x.ItemStatus == QueueItemStatus.Failed);
        #endregion

        #region Input properties
        public IReadOnlyList<string> ResolutionChoices => ResolutionOptions;

        private string _videoPath = string.Empty;
        public string VideoPath
        {
            get => _videoPath;
            set
            {
                if (_videoPath != value)
                {
                    _videoPath = value;
                    OnPropertyChanged();
                    OnPropertyChanged(nameof(HasVideo));
                    OnPropertyChanged(nameof(CanAddToQueue));
                    OnPropertyChanged(nameof(CanAnalyze));
                    LoadVideoInfo();
                    OnCanExecuteChanged();
                }
            }
        }

        private string _videoInfo = string.Empty;
        public string VideoInfo
        {
            get => _videoInfo;
            set { if (_videoInfo != value) { _videoInfo = value; OnPropertyChanged(); } }
        }

        private string? _videoFileUri;
        public string? VideoFileUri
        {
            get => _videoFileUri;
            private set { if (_videoFileUri != value) { _videoFileUri = value; OnPropertyChanged(); } }
        }

        private string _prompt = string.Empty;
        public string Prompt
        {
            get => _prompt;
            set { if (_prompt != value) { _prompt = value; OnPropertyChanged(); } }
        }

        private string _negativePrompt = "pc game, console game, video game, ugly, 3d render, photo, still, static, slow, distorted, seam, warped, low quality, blurry, artifacts, watermark, text";
        public string NegativePrompt
        {
            get => _negativePrompt;
            set { if (_negativePrompt != value) { _negativePrompt = value; OnPropertyChanged(); } }
        }

        private string _resolution = "960×480";
        public string Resolution
        {
            get => _resolution;
            set { if (_resolution != value) { _resolution = value; OnPropertyChanged(); } }
        }

        private int _frameCap = 121;
        public int FrameCap
        {
            get => _frameCap;
            set { var v = value < 1 ? 1 : value; if (_frameCap != v) { _frameCap = v; OnPropertyChanged(); } }
        }

        private double _stereoStrength = 0.12;
        public double StereoStrength
        {
            get => _stereoStrength;
            set { var v = Math.Clamp(value, 0, 0.5); if (Math.Abs(_stereoStrength - v) > 1e-6) { _stereoStrength = v; OnPropertyChanged(); } }
        }

        public bool HasVideo => !string.IsNullOrEmpty(VideoPath) && File.Exists(VideoPath);
        public bool CanAddToQueue => HasVideo;
        public bool CanAnalyze => HasVideo && !IsAnalyzing && !IsProcessing;

        private bool _isAnalyzing;
        public bool IsAnalyzing
        {
            get => _isAnalyzing;
            set
            {
                if (_isAnalyzing != value)
                {
                    _isAnalyzing = value;
                    OnPropertyChanged();
                    OnPropertyChanged(nameof(CanAnalyze));
                    OnCanExecuteChanged();
                }
            }
        }
        #endregion

        #region Queue properties
        public ObservableCollection<Vr180QueueItem> Queue => _queue;

        private bool _isProcessingQueue;
        public bool IsProcessingQueue
        {
            get => _isProcessingQueue;
            private set { if (_isProcessingQueue != value) { _isProcessingQueue = value; OnPropertyChanged(); OnCanExecuteChanged(); } }
        }

        private string _queueStatus = string.Empty;
        public string QueueStatus { get => _queueStatus; private set { if (_queueStatus != value) { _queueStatus = value; OnPropertyChanged(); } } }

        public bool HasQueueItems => _queue.Any();
        #endregion

        #region File selection
        private async void SelectVideo()
        {
            var initialDir = _settingsService.Settings?.VideoGeneratorImageFolder;
            if (string.IsNullOrEmpty(initialDir) || !Directory.Exists(initialDir))
                initialDir = Environment.GetFolderPath(Environment.SpecialFolder.MyVideos);

            var path = await _fileDialogService.OpenFileDialogAsync(
                "Select Flat Video",
                "Video Files|*.mp4;*.avi;*.mov;*.mkv;*.webm|All Files|*.*",
                initialDir,
                persistKey: "vr180.video");

            if (path != null)
            {
                VideoPath = path;
                AddLog($"Input video: {Path.GetFileName(path)}");
            }
        }

        public void SetVideoFromPath(string path)
        {
            if (string.IsNullOrWhiteSpace(path) || !File.Exists(path)) return;
            VideoPath = path;
            AddLog($"Input video: {Path.GetFileName(path)}");
        }

        private void LoadVideoInfo()
        {
            if (!HasVideo)
            {
                VideoInfo = string.Empty;
                VideoFileUri = null;
                return;
            }
            var fi = new FileInfo(VideoPath);
            VideoInfo = $"{fi.Name} • {fi.Length / 1024 / 1024.0:F1}MB";
            VideoFileUri = VideoPath;
        }
        #endregion

        #region Analysis
        private async Task AnalyzeAsync()
        {
            if (!CanAnalyze) return;

            IsAnalyzing = true;
            _analyzeCts?.Dispose();
            _analyzeCts = new CancellationTokenSource();
            var token = _analyzeCts.Token;

            string? framePath = null;
            try
            {
                ProcessingStatus = "Extracting first frame…";
                framePath = ExtractFirstFrame(VideoPath);
                if (framePath == null || !File.Exists(framePath))
                    throw new Exception("Could not extract a frame from the video (is FFmpeg installed?).");

                var baseUrl = _settingsService.Settings?.LMStudioSettings?.BaseUrl ?? "http://alien:8080";
                await _lmStudioService.SetBaseUrlAsync(baseUrl);

                var models = await _lmStudioService.GetAvailableModelsAsync(token);
                var selectedModel = _settingsService.Settings?.LMStudioSettings?.SelectedModel ?? string.Empty;
                if (string.IsNullOrEmpty(selectedModel) && models.Count > 0)
                    selectedModel = models[0].Id ?? models[0].Name ?? string.Empty;

                if (string.IsNullOrEmpty(selectedModel))
                {
                    System.Windows.MessageBox.Show("No LM Studio model available. Please ensure LM Studio is running and a model is loaded.",
                        "LM Studio Unavailable", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                AddLog($"Sending first frame to {_lmStudioService.DescribeTarget(selectedModel)}");

                var promptFilePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
                    "prompts", "prompt2json", "vr180.md");
                if (!File.Exists(promptFilePath))
                    throw new FileNotFoundException($"System prompt not found: {promptFilePath}");
                var systemPrompt = await File.ReadAllTextAsync(promptFilePath, token);

                var result = await _lmStudioService.AnalyzeImageWithSystemPromptAsync(
                    selectedModel,
                    framePath,
                    "Describe this scene as a full 360° environment for VR outpainting.",
                    systemPrompt,
                    maxTokens: 4000,
                    cancellationToken: token);

                var cleaned = CleanOutput(result);
                if (!string.IsNullOrWhiteSpace(cleaned))
                {
                    Prompt = cleaned;
                    AddLog($"Prompt generated ({cleaned.Length} chars)");
                }
                else AddLog("WARNING: Analysis returned empty result");
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                AddLog($"ERROR during analysis: {ex.Message}");
                System.Windows.MessageBox.Show($"Analysis failed:\n{ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                if (framePath != null) { try { File.Delete(framePath); } catch { } }
                ProcessingStatus = string.Empty;
                IsAnalyzing = false;
                _analyzeCts?.Dispose();
                _analyzeCts = null;
            }
        }

        /// <summary>Extracts the first frame of a video to a temp PNG via FFmpeg. Returns null on failure.</summary>
        private string? ExtractFirstFrame(string videoPath)
        {
            try
            {
                var ffmpegPath = FindFFmpeg();
                if (ffmpegPath == null) return null;

                var tempPath = Path.Combine(Path.GetTempPath(), $"flippix_vr180_frame_{Guid.NewGuid():N}.png");
                var startInfo = new ProcessStartInfo
                {
                    FileName = ffmpegPath,
                    Arguments = $"-y -i \"{videoPath}\" -frames:v 1 -q:v 2 \"{tempPath}\"",
                    UseShellExecute = false,
                    RedirectStandardError = true,
                    CreateNoWindow = true
                };
                using var process = Process.Start(startInfo);
                if (process == null) return null;
                process.StandardError.ReadToEnd();
                process.WaitForExit(30000);

                return File.Exists(tempPath) && new FileInfo(tempPath).Length > 0 ? tempPath : null;
            }
            catch (Exception ex)
            {
                AddLog($"Frame extraction failed: {ex.Message}");
                return null;
            }
        }

        private static string CleanOutput(string text)
        {
            if (string.IsNullOrWhiteSpace(text)) return text;
            text = text.Replace("**", "").Trim();
            var lower = text.ToLowerInvariant();
            if (lower.StartsWith("prompt:") || lower.StartsWith("prompt :"))
                text = text.Substring(text.IndexOf(':') + 1).Trim();
            return text;
        }
        #endregion

        #region Queue management
        private void AddToQueue()
        {
            if (!CanAddToQueue) return;

            var (w, h) = ResolutionDimsFor(Resolution);
            var item = new Vr180QueueItem
            {
                VideoPath = VideoPath,
                Prompt = Prompt ?? string.Empty,
                NegativePrompt = NegativePrompt,
                EquirectWidth = w,
                EquirectHeight = h,
                FrameCap = FrameCap,
                StereoStrength = StereoStrength,
                Seed = -1,
                ItemStatus = QueueItemStatus.Pending
            };

            _queue.Add(item);
            SaveQueueToFile();
            AddLog($"Added to queue: {item.DisplayText}");
            UpdateQueueStatus();

            if (!IsProcessingQueue) _ = ProcessQueueAsync();
        }

        private void RemoveQueueItem(Vr180QueueItem? item)
        {
            if (item != null && item.ItemStatus != QueueItemStatus.Processing)
            {
                _queue.Remove(item);
                SaveQueueToFile();
                UpdateQueueStatus();
            }
        }

        private void UpdateQueueStatus()
        {
            var pending = _queue.Count(x => x.ItemStatus == QueueItemStatus.Pending);
            var completed = _queue.Count(x => x.ItemStatus == QueueItemStatus.Completed);
            var failed = _queue.Count(x => x.ItemStatus == QueueItemStatus.Failed);
            QueueStatus = _queue.Count == 0 ? string.Empty : $"{pending} pending • {completed} done • {failed} failed";
            OnPropertyChanged(nameof(HasFailedItems));
            OnCanExecuteChanged();
        }

        private void ClearQueue()
        {
            _queueCts?.Cancel();
            _queue.Clear();
            SaveQueueToFile();
            UpdateQueueStatus();
            AddLog("Queue cleared");
        }

        private void StopQueue() => _queueCts?.Cancel();

        private async Task ReprocessAllFailedAsync()
        {
            var failed = _queue.Where(x => x.ItemStatus == QueueItemStatus.Failed).ToList();
            if (!failed.Any()) return;
            foreach (var item in failed) item.ItemStatus = QueueItemStatus.Pending;
            UpdateQueueStatus();
            SaveQueueToFile();
            if (!IsProcessingQueue) await ProcessQueueAsync();
        }

        private async Task ProcessQueueAsync()
        {
            if (IsProcessingQueue) return;

            IsProcessingQueue = true;
            _queueCts?.Dispose();
            _queueCts = new CancellationTokenSource();
            var token = _queueCts.Token;

            WorkflowQueueCoordinator.WorkflowLease lease;
            try
            {
                AddLog("Waiting for other workflows to finish...");
                lease = await _workflowCoordinator.AcquireAsync("Vr180", token);
            }
            catch (OperationCanceledException)
            {
                IsProcessingQueue = false;
                OnCanExecuteChanged();
                return;
            }

            AddLog("Starting VR 180 queue...");
            using (lease)
            try
            {
                Vr180QueueItem? item;
                while (!token.IsCancellationRequested &&
                       (item = _queue.FirstOrDefault(x => x.ItemStatus == QueueItemStatus.Pending)) != null)
                {
                    item.ItemStatus = QueueItemStatus.Processing;
                    UpdateQueueStatus();
                    SaveQueueToFile();
                    try
                    {
                        await GenerateSingleVideoAsync(item, token);
                        item.ItemStatus = QueueItemStatus.Completed;
                        AddLog($"Completed: {item.DisplayText}");
                    }
                    catch (OperationCanceledException)
                    {
                        item.ItemStatus = QueueItemStatus.Pending;
                        break;
                    }
                    catch (Exception ex)
                    {
                        var shouldRetry = await TryHandleCrashAndRetryAsync(item, ex);
                        if (shouldRetry)
                        {
                            item.ItemStatus = QueueItemStatus.Pending;
                            AddLog("Item reset to Pending — will retry after ComfyUI restart");
                        }
                        else
                        {
                            item.ItemStatus = QueueItemStatus.Failed;
                            item.ErrorMessage = ex.Message;
                            AddLog($"FAILED: {ex.Message}");
                        }
                    }
                    UpdateQueueStatus();
                    SaveQueueToFile();
                }
            }
            finally
            {
                IsProcessingQueue = false;
                AddLog("Queue processing finished.");
                OnCanExecuteChanged();
            }
        }
        #endregion

        #region Queue persistence
        private void SaveQueueToFile()
        {
            try
            {
                var dir = Path.GetDirectoryName(QueueFilePath);
                if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
                File.WriteAllText(QueueFilePath,
                    JsonSerializer.Serialize(_queue.ToList(), new JsonSerializerOptions { WriteIndented = true }));
            }
            catch (Exception ex) { AddLog($"Error saving queue: {ex.Message}"); }
        }

        private void LoadQueueFromFile()
        {
            try
            {
                if (!File.Exists(QueueFilePath)) return;
                var items = JsonSerializer.Deserialize<List<Vr180QueueItem>>(File.ReadAllText(QueueFilePath));
                if (items?.Any() != true) return;
                _queue.Clear();
                foreach (var item in items)
                {
                    if (item.ItemStatus == QueueItemStatus.Processing) item.ItemStatus = QueueItemStatus.Pending;
                    _queue.Add(item);
                }
                UpdateQueueStatus();
                AddLog($"Queue loaded: {_queue.Count} items");
                if (_queue.Any(x => x.ItemStatus == QueueItemStatus.Pending))
                    _ = ProcessQueueAsync();
            }
            catch (Exception ex) { AddLog($"Error loading queue: {ex.Message}"); }
        }
        #endregion

        #region Generation
        private async Task GenerateSingleVideoAsync(Vr180QueueItem item, CancellationToken token)
        {
            try
            {
                IsProcessing = true;
                HasResult = false;
                ResultVideoPath = string.Empty;
                ResultVideoInfo = string.Empty;
                ProcessingProgress = 0;
                ProcessingStatus = "Preparing VR 180 workflow...";

                AddLog($"=== VR 180: {item.DisplayText} ===");

                ProcessingStatus = "Checking ComfyUI...";
                if (!await _comfyUIService.DetectAndRestartIfCrashedAsync(s => AddLog($"[Auto-Restart] {s}")))
                    throw new Exception("ComfyUI is not running.");
                if (!_comfyUIService.IsConnected)
                {
                    ProcessingStatus = "Connecting to ComfyUI...";
                    await _comfyUIService.ConnectAsync();
                }

                var workflowPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, WorkflowFileName);
                if (!File.Exists(workflowPath))
                    throw new FileNotFoundException($"Workflow file not found: {workflowPath}");
                var workflowJson = await File.ReadAllTextAsync(workflowPath, token);

                ProcessingStatus = "Uploading video...";
                ProcessingProgress = 10;

                AddLog("Uploading flat video...");
                var uploadedVideo = await _comfyUIService.UploadVideoAsync(item.VideoPath);
                if (string.IsNullOrEmpty(uploadedVideo))
                    throw new Exception("Failed to upload video.");
                AddLog($"Video uploaded: {uploadedVideo}");

                var runSeed = item.Seed >= 0 ? item.Seed : new Random().NextInt64(0, long.MaxValue);

                var json = workflowJson;
                WorkflowNodeUpdater.UpdateNodeInput(ref json, LoadVideoNode, "video", uploadedVideo);
                WorkflowNodeUpdater.UpdateNodeInput(ref json, LoadVideoNode, "frame_load_cap", item.FrameCap);
                WorkflowNodeUpdater.UpdateNodeInput(ref json, EquirectNode, "equirect_width", item.EquirectWidth);
                WorkflowNodeUpdater.UpdateNodeInput(ref json, EquirectNode, "equirect_height", item.EquirectHeight);
                WorkflowNodeUpdater.UpdateNodeInput(ref json, PositiveNode, "text", item.Prompt ?? string.Empty);
                WorkflowNodeUpdater.UpdateNodeInput(ref json, NegativeNode, "text", item.NegativePrompt ?? string.Empty);
                WorkflowNodeUpdater.UpdateNodeInput(ref json, SeedNode, "noise_seed", runSeed);
                AddLog($"✓ {item.EquirectWidth}×{item.EquirectHeight} equirect · {item.FrameCap} frames · seed={runSeed}");

                var workflow = JsonSerializer.Deserialize<JsonElement>(json);

                ProcessingProgress = 20;
                ProcessingStatus = "Generating 360° panorama...";
                var progress = new Progress<FlipPix.ComfyUI.Models.ProgressMessage>(msg =>
                {
                    if (msg.Data?.Value != null && msg.Data?.Max != null)
                    {
                        var pct = (double)msg.Data.Value / msg.Data.Max * 100;
                        Application.Current.Dispatcher.Invoke(() =>
                        {
                            ProcessingProgress = 20 + pct * 0.75;
                            ProcessingStatus = $"Generating: {msg.Data.Value}/{msg.Data.Max}";
                        });
                    }
                });

                var existingColor = GetExistingVideoFiles("*.mp4", OutputSubfolder);
                var existingDepth = GetExistingVideoFiles("*.mp4", DepthSubfolder);
                var promptId = await _comfyUIService.ExecuteWorkflowAsync(workflow, progress);
                AddLog($"Workflow submitted, ID: {promptId}");

                ProcessingProgress = 92;
                ProcessingStatus = "Retrieving panorama + depth...";

                var (colorPath, depthPath) = await RetrievePromptOutputsAsync(promptId, existingColor, existingDepth);
                if (colorPath == null || !File.Exists(colorPath))
                    throw new Exception("No panorama output was generated.");
                AddLog(depthPath != null
                    ? $"Got color + depth ({Path.GetFileName(colorPath)}, {Path.GetFileName(depthPath)})"
                    : $"Got color only ({Path.GetFileName(colorPath)}) — depth missing, will fall back to mono SBS");

                var outputDir = Path.Combine(
                    _settingsService.Settings?.OutputFolderPath ?? Path.GetTempPath(), "Vr180");
                Directory.CreateDirectory(outputDir);
                var finalPath = Path.Combine(outputDir, $"VR180_SBS_{DateTime.Now:yyyyMMdd_HHmmss}.mp4");

                ProcessingProgress = 96;
                bool stereo = depthPath != null && File.Exists(depthPath) && item.StereoStrength > 0.001;
                ProcessingStatus = stereo
                    ? "Building side-by-side VR180 (depth stereo)..."
                    : "Building side-by-side VR180 (mono)...";
                var built = await BuildSbsVr180Async(colorPath, stereo ? depthPath : null,
                    item.StereoStrength, finalPath, token);
                if (!built)
                {
                    AddLog("SBS build failed — saving the mono panorama as-is.");
                    File.Copy(colorPath, finalPath, true);
                    stereo = false;
                }

                item.OutputVideoPath = finalPath;
                ResultVideoPath = finalPath;
                await LocalCopyService.CopyVideoAsync(finalPath);
                HasResult = true;
                var fi = new FileInfo(finalPath);
                ResultVideoInfo = $"VR 180 • {(stereo ? "SBS 3D (depth)" : "SBS mono")} • {fi.Length / 1024 / 1024.0:F1}MB";
                ProcessingProgress = 100;
                ProcessingStatus = "VR 180 Complete!";
                AddLog($"=== Complete: {finalPath} ===");
            }
            catch (Exception ex)
            {
                AddLog($"ERROR: {ex.Message}");
                ProcessingStatus = "Error";
                throw;
            }
            finally
            {
                IsProcessing = false;
            }
        }

        /// <summary>
        /// Resolves the workflow's two outputs for this prompt: the color panorama (vr180/)
        /// and the Video-Depth-Anything depth pass (vr180_depth/). Tries the history API first,
        /// then falls back to scanning the output subfolders. Depth may be null if the pass
        /// didn't run (e.g. node not installed) — caller then falls back to mono SBS.
        /// </summary>
        private async Task<(string? Color, string? Depth)> RetrievePromptOutputsAsync(
            string promptId, HashSet<string> existingColor, HashSet<string> existingDepth)
        {
            string? color = null, depth = null;
            try
            {
                var files = await _comfyUIService.HttpClient.GetOutputFilesForPromptAsync(promptId);
                var videos = files.Where(f => f.EndsWith(".mp4", StringComparison.OrdinalIgnoreCase)).ToList();
                var depthView = videos.FirstOrDefault(f => f.IndexOf("depth", StringComparison.OrdinalIgnoreCase) >= 0);
                var colorView = videos.FirstOrDefault(f => f.IndexOf("depth", StringComparison.OrdinalIgnoreCase) < 0);
                if (colorView != null) color = await ResolveViewPathAsync(colorView);
                if (depthView != null) depth = await ResolveViewPathAsync(depthView);
            }
            catch (Exception ex) { AddLog($"History lookup failed: {ex.Message}"); }

            // Filesystem fallback for whichever output the history API didn't yield.
            if (color == null)
            {
                AddLog("Polling filesystem for color output...");
                color = await WaitForNewVideoAsync(existingColor, "*.mp4",
                    TimeSpan.FromMinutes(30), TimeSpan.FromSeconds(5), OutputSubfolder);
            }
            if (depth == null)
            {
                // Short poll — depth finishes alongside color; don't block long if absent.
                depth = await WaitForNewVideoAsync(existingDepth, "*.mp4",
                    TimeSpan.FromSeconds(20), TimeSpan.FromSeconds(2), DepthSubfolder);
            }
            return (color, depth);
        }

        /// <summary>Resolves a ComfyUI "subfolder/filename" output path to a local file, downloading via /view if needed.</summary>
        private async Task<string?> ResolveViewPathAsync(string viewPath)
        {
            var parts = viewPath.Split('/');
            var filename = parts.Last();
            var subfolder = parts.Length > 1 ? string.Join("/", parts.Take(parts.Length - 1)) : "";

            var settings = _settingsService.Settings;
            if (settings != null)
            {
                var baseUrl = GetComfyUIBaseUrl();
                bool isRemote = IsComfyUIRemote(new Uri(baseUrl).Host);
                var outputFolder = settings.ResolveOutputFolder(isRemote);
                if (!string.IsNullOrEmpty(outputFolder))
                {
                    var local = Path.Combine(outputFolder, viewPath.Replace('/', Path.DirectorySeparatorChar));
                    if (File.Exists(local)) { await WaitForFileStableAsync(local); return local; }
                }
            }

            try
            {
                var bytes = await _comfyUIService.HttpClient.DownloadViewFileAsync(filename, subfolder, "output");
                if (bytes != null && bytes.Length > 0)
                {
                    var tmp = Path.Combine(Path.GetTempPath(), $"flippix_vr180_{Guid.NewGuid():N}_{filename}");
                    await File.WriteAllBytesAsync(tmp, bytes);
                    return tmp;
                }
            }
            catch (Exception ex) { AddLog($"Download of {viewPath} failed: {ex.Message}"); }
            return null;
        }

        /// <summary>
        /// Builds a side-by-side VR180 file from the mono equirect panorama. Each eye is reprojected
        /// from equirect into a filled 180° fisheye (v360) so the scene fills the frame edge-to-edge,
        /// the way headset VR180 expects. When a depth video is supplied, real left/right parallax is
        /// synthesized first via FFmpeg's displace filter (DIBR) in equirect space; otherwise the mono
        /// view is duplicated to both eyes. Returns false if FFmpeg is missing or the build fails.
        /// </summary>
        private async Task<bool> BuildSbsVr180Async(string colorPath, string? depthPath, double strength, string outPath, CancellationToken token)
        {
            var ffmpeg = FindFFmpeg();
            if (ffmpeg == null) { AddLog("FFmpeg not found — cannot build SBS VR180."); return false; }

            // Square eye = panorama height; fall back to 512 if probing fails.
            var (_, ch) = GetVideoDimensions(colorPath);
            int eye = ch > 0 ? (ch / 2) * 2 : 512; // keep even
            // equirect → filled 180° fisheye per eye
            string Fish(string inLbl, string outLbl) =>
                $"[{inLbl}]v360=e:fisheye:h_fov=180:v_fov=180:w={eye}:h={eye}[{outLbl}];";

            var psi = new ProcessStartInfo
            {
                FileName = ffmpeg,
                UseShellExecute = false,
                RedirectStandardError = true,
                CreateNoWindow = true
            };
            psi.ArgumentList.Add("-y");
            psi.ArgumentList.Add("-i"); psi.ArgumentList.Add(colorPath);

            string filter;
            if (depthPath != null)
            {
                psi.ArgumentList.Add("-i"); psi.ArgumentList.Add(depthPath);
                var s = strength.ToString("0.####", System.Globalization.CultureInfo.InvariantCulture);
                // depth → opposite horizontal displacement maps per eye (parallax) in equirect space,
                // then reproject each eye to a 180° fisheye and stack side-by-side.
                filter =
                    "[1:v]format=gray,split=3[d1][d2][d3];" +
                    $"[d1]lutyuv=y='clip(128+(val-128)*{s},0,255)',format=gbrp[xl];" +
                    $"[d2]lutyuv=y='clip(128-(val-128)*{s},0,255)',format=gbrp[xr];" +
                    "[d3]lutyuv=y=128,format=gbrp[ym];" +
                    "[0:v]format=gbrp,split=2[c1][c2];" +
                    "[c1][xl][ym]displace=edge=smear[el];" +
                    "[c2][xr][ym]displace=edge=smear[er];" +
                    Fish("el", "fl") + Fish("er", "fr") +
                    "[fl][fr]hstack=2,format=yuv420p[v]";
            }
            else
            {
                filter =
                    "[0:v]split=2[c1][c2];" +
                    Fish("c1", "fl") + Fish("c2", "fr") +
                    "[fl][fr]hstack=2,format=yuv420p[v]";
            }

            psi.ArgumentList.Add("-filter_complex"); psi.ArgumentList.Add(filter);
            psi.ArgumentList.Add("-map"); psi.ArgumentList.Add("[v]");
            psi.ArgumentList.Add("-c:v"); psi.ArgumentList.Add("libx264");
            psi.ArgumentList.Add("-crf"); psi.ArgumentList.Add("18");
            psi.ArgumentList.Add("-pix_fmt"); psi.ArgumentList.Add("yuv420p");
            psi.ArgumentList.Add(outPath);

            try
            {
                using var proc = Process.Start(psi);
                if (proc == null) { AddLog("Failed to start FFmpeg."); return false; }
                var stderrTask = proc.StandardError.ReadToEndAsync();
                await proc.WaitForExitAsync(token);
                var stderr = await stderrTask;
                if (proc.ExitCode != 0)
                {
                    AddLog($"FFmpeg SBS failed (exit {proc.ExitCode}): {Tail(stderr, 400)}");
                    return false;
                }
                return File.Exists(outPath) && new FileInfo(outPath).Length > 0;
            }
            catch (OperationCanceledException) { try { if (File.Exists(outPath)) File.Delete(outPath); } catch { } throw; }
            catch (Exception ex) { AddLog($"FFmpeg SBS error: {ex.Message}"); return false; }
        }

        private static string Tail(string s, int n) =>
            string.IsNullOrEmpty(s) ? string.Empty : (s.Length <= n ? s : s.Substring(s.Length - n));

        /// <summary>Equirect (width, height) — always 2:1 — for a resolution preset.</summary>
        private static (int Width, int Height) ResolutionDimsFor(string resolution) => resolution switch
        {
            "960×480" => (960, 480),
            "1280×640" => (1280, 640),
            "1600×800" => (1600, 800),
            "1920×960" => (1920, 960),
            _ => (960, 480)
        };
        #endregion

        protected override void OnCanExecuteChanged()
        {
            base.OnCanExecuteChanged();
            AnalyzeCommand.NotifyCanExecuteChanged();
            GenerateVideoCommand.NotifyCanExecuteChanged();
            RemoveQueueItemCommand.NotifyCanExecuteChanged();
            ClearQueueCommand.NotifyCanExecuteChanged();
            StopQueueCommand.NotifyCanExecuteChanged();
            StartQueueCommand.NotifyCanExecuteChanged();
            ReprocessAllFailedCommand.NotifyCanExecuteChanged();
            PlayVideoCommand.NotifyCanExecuteChanged();
            OpenResultFolderCommand.NotifyCanExecuteChanged();
            SendToEditCameraCommand.NotifyCanExecuteChanged();
        }
    }
}
